const myDate = new Date();
console.log(myDate.getDate());
console.log(myDate.getVarDate());
console.log(myDate.getFullYear());
console.log(myDate.getHours());
console.log(myDate.getMinutes());
console.log(myDate.getSeconds());
console.log(myDate.getMilliseconds());
console.log(myDate.getTime());
console.log(myDate.getDay());